### ISSUE TITLE
Does not install Ubuntu 18.04

### ISSUE THREAD

**Issue by dkeetonx** [mmtrt/cncra2yr#1]
```
$ cncra2yr
You need to connect this snap to the wine-platform snap.

snap disconnect cncra2yr:wine-platform-plug
snap install wine-platform
snap connect cncra2yr:wine-platform-plug wine-platform:wine-base-stable
```

**Comment by dkeetonx** [comment]
Yes. I get a dialog that says  "Could not find a Direct3D device that supports the XNA Framework Reach profile."

The client does render though, but there is no mouse cursor.

Did you know that the client will run with mono directly from Linux and it will execute wine-dta.sh rather than gamemd-spawn.exe when it's running on Linux?

```
env MONO_IOMAP=all  mono --debug Resources/clientogl.exe
```

**Comment by mmtrt** [comment]
Yeah I did tried these three clients before selecting right one though I did forgot about ddraw dlloverride, thanks I'll retry ogl client atm I'm fixing wine issue on i386 systems failing to launch snaps though I'll implement that changes.

**Comment by mmtrt** [comment]
Tried mono with ogl client it is not playing nice with snap env so with current xna client it is working fine now.

**Comment by mmtrt** [comment]
closing this as the game works fine.
