### ISSUE TITLE
Custom maps not appearing in skirmish map list

### ISSUE THREAD

**Issue by sean-whiley** [mmtrt/cncra2yr#10]
Hi there!

First of all just wanted to voice my appreciation for this project! This old classic has actually been easier to get running on Ubuntu than on Windows 10!

I have some old custom maps that were built on FinalAlert 2 years ago. I have copied them into the "Maps/Custom" folder. Their original file type is .mpr but I have also used FinalAlert 2 to re-save one as .yrm just to test.

I have checked their [Basic] Gamemode= is standard (in some cases it is: GameMode=standard, cooperative, teamgame - is that okay?).

So no matter what I try I can't get these maps to appear in the list of available Skirmish maps. 

What am I doing wrong?

Thanks in advance!

**Comment by mmtrt** [comment]
Did you tried checking for your map on the different game types see if it shows. And also try saving map with `.map` extension see if this helps.

![gametype png 251e288930eacbe3ab69442e3038c848](https://user-images.githubusercontent.com/2322598/62846597-d4331f00-bcea-11e9-9bfc-d92e0fc8b8f4.png)

**Comment by sean-whiley** [comment]
Thank you for your quick reply! I have managed to make the maps playable. I did this by renaming the .mpr extension to .map. I still havn't been able to get them to appear in all of the correct game types (Free For All is not playing ball) but at least I can now make these custom maps playable again! Thank you so much, keep up the good work!
