### ISSUE TITLE
5.1 update constantly loops installer

### ISSUE THREAD

**Issue by vocatus** [mmtrt/cncra2yr#11]
Linux Mint 19.1 x64 MATE. Latest release (prompted me to update when launching RA2) just loops the installer over and over. It downloads all the files, then appears to be complete, but when I click the icon in the Start Menu / Mint Menu, it just re-launches the installer. 

Am I doing something wrong?

**Comment by mmtrt** [comment]
Not at all since I forgot to remove updater dir after copying updated files over should be fix now, mean while you can fix it by removing the `updater` folder from `$HOME/snap/cncra2yr/common/.wine/drive_c/Westwood/RA2/` or you can wait for snap update to land in the repos.

**Comment by mmtrt** [comment]
fix is now released in snap stable repo.

**Comment by vocatus** [comment]
Awesome, thanks for the fast response.
