### ISSUE TITLE
Fails to launch with popup error message

### ISSUE THREAD

**Issue by vocatus** [mmtrt/cncra2yr#12]
Hi there, I get this error when launching the game on a Mint 19.2 x64 system running MATE desktop:

> Yuri's Revenge has crashed. Error message:
> 
> Could not load file or assembly 'Microsoft.Xna.Framework.Game, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842ccf8be1de50553' or one of its dependencies. File not found.

**Comment by mmtrt** [comment]
did you tried fresh install by removing snap data dir which is in `/home/$USER/snap/cncra2yr` or this happens with old game installed.

**Comment by vocatus** [comment]
This was on a fresh install on a new system (got a new laptop). 

I did the following:

    sudo snap remove cncra2yr

Then deleted `/home/$USER/snap/cncra2yr` , then re-installed and placed the required files in the directory. 

I launched the game successfully, and it said "there is an update available to v5.4" I ran the update, the game quit and then tried to restart, but got the error: "Your system is missing .NET 4.5"

**Comment by vocatus** [comment]
I restarted the computer, then attempted to run again, and received this error:

    Yuri's revenge has crashed. Error message:
    XNA Framework Reach profile supports a maximum Texture2D size of 2048

**Comment by mmtrt** [comment]
I haven't tested game yet so I'll check for this issue will post fix.

**Comment by vocatus** [comment]
update: I did another complete removal and fresh installation. If I *don't* click "yes, update to 5.4" then the game works. But if I try to do the update, that's when all the errors happen. Thanks again!

**Comment by mmtrt** [comment]
That's weird I just updated to `5.4` and its working fine here no issues like that.

Did you tried changing renderer or game launcher does not work for you.

**Comment by vocatus** [comment]
Hi @mmtrt , this seems to have resolved itself (I didn't do anything)...strange. I'll close it out, thanks again.
