### ISSUE TITLE
How to save game settings in skirmish mode?

### ISSUE THREAD

**Issue by stulluk** [mmtrt/cncra2yr#13]
When I setup my Skirmish game ( specific map, specific number of players, their colors...etc ); and if I exit and restart the game, all my settings is lost.

Is this normal or a bug?

**Comment by mmtrt** [comment]
I get this similar in `windows` as well so its normal I guess and this could be due to other setting entries missing/not implement in `SkirmishSettings.ini` file under client dir.

**Comment by stulluk** [comment]
I can permanently store my skirmish settings when I run RA2 under Linux Mint with Wine4.0. The issue with running RA2 under Wine2/3/4 is, graphics suddenly stops but audio continues. And this happens sporadically ( GTX1050 GPU ).

However, this issue does not happen with your snap, thank you very much for it.

Below is the contents of my SkirmishSettings.ini file.

[Player]
Info=,9,1,2,0,0,False,0

[AIPlayers]
0=Hard AI,1,3,3,0,0,True,1
1=Hard AI,1,4,6,0,0,True,2
2=Hard AI,1,2,7,0,0,True,3

[Settings]
Map=726d1d7d2f7e0673e54c0c91ae202f9ec670a4ea
GameMode=Battle

What could be missing in this file , so I can fix it?

**Comment by mmtrt** [comment]
I'm not sure about that only developers of cncnet yr client would know about this so I think it would be a good idea to report this to them.

**Comment by mmtrt** [comment]
Issue is resolved by upstream changes in client.
