### ISSUE TITLE
Game fails to launch, complains about color depth. 

### ISSUE THREAD

**Issue by belthesar** [mmtrt/cncra2yr#18]
Hi! I don't seem to be able to launch into a game of RA2.  When launching the game, it complains about needing 16-bit color depth.  I don't seem to have a decent way to reconfigure my X server to be in 16-bit color depth, and as I've been informed by other research that it can limit GPU acceleration. Do you have any suggestions?

**Comment by mmtrt** [comment]
I'm not seeing such issue here how are you launching RA2 by selecting RA2 checkbox?

**Comment by belthesar** [comment]
Fixed on my end, this was an issue with the version of ddraw that was selected. "Automatic" would not choose the best driver.
