### ISSUE TITLE
Cannot running on Fedora 32 - Could not find a Direct3D device that supports the XNA Framework Reach profile

### ISSUE THREAD

**Issue by maprangzth** [mmtrt/cncra2yr#20]
Could not find a Direct3D device that supports the XNA Framework Reach profile:

![yuri-snap-error](https://user-images.githubusercontent.com/1495634/81492519-a521fc00-92c2-11ea-93df-6e08c251a5ca.png)

**Comment by mmtrt** [comment]
update snap then try launching with opengl

`snap refresh`

`snap run cncra2yr.cncra2yrogl`

**Comment by maprangzth** [comment]
Still error but a new message
```
# snap run cncra2yr.cncra2yrogl

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Sdl' threw an exception. ---> System.Exception: Failed to load SDL library.
   at Sdl.GetNativeLibrary()
   at Sdl..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.SdlGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.GamePlatform.PlatformCreate(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
   at DTAClient.DXGUI.GameClass..ctor()
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 4b at address 0x7b43c92c (thread 004b), starting debugger...
Can't attach process 004a: error 5
```
![cncra2yrogl](https://user-images.githubusercontent.com/1495634/81896466-dcecb480-95de-11ea-998d-c1d71a9662dd.png)

**Comment by mmtrt** [comment]
try fresh install snap maybe xna framework is borked in wineprefix.

`snap remove cncra2yr --purge`

**Comment by maprangzth** [comment]
> try fresh install snap maybe xna framework is borked in wineprefix.
> 
> `snap remove cncra2yr --purge`

still have an error :(

**Comment by mmtrt** [comment]
I'm out of ideas,

which gpu you have and do you have i386 driver pkgs installed could be that.

**Comment by maprangzth** [comment]
My Laptop is a Lenovo ThinkPad L380. I'm not sure, may it be because of On-Board GPU?

![hw-info](https://user-images.githubusercontent.com/1495634/81938384-07f6f880-961f-11ea-8d22-41baa0596445.png)

**Comment by maprangzth** [comment]
> My Laptop is a Lenovo ThinkPad L380. I'm not sure, may it be because of On-Board GPU?
> 
> ![hw-info](https://user-images.githubusercontent.com/1495634/81938384-07f6f880-961f-11ea-8d22-41baa0596445.png)

```bash
inxi -CGS
System:    Host: fedora-l380 Kernel: 5.6.11-300.fc32.x86_64 x86_64 bits: 64 Desktop: Gnome 3.36.2
           Distro: Fedora release 32 (Thirty Two)
CPU:       Topology: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP L2 cache: 8192 KiB
           Speed: 800 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800 8: 800
Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
           Device-2: Acer Integrated Camera type: USB driver: uvcvideo
           Display: x11 server: Fedora Project X.org 1.20.8 driver: modesetting unloaded: fbdev,vesa resolution:
           1: 1366x768~60Hz 2: 1920x1080~60Hz
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.0.6
```

**Comment by maprangzth** [comment]
I try it again on this day, it's work for me :)
