### ISSUE TITLE
Cannot Skirmish

### ISSUE THREAD

**Issue by edos4** [mmtrt/cncra2yr#22]
When I try to Launch Game on Skirmish, it says "A game is in progress". Then it returns to the Skirmish menu. 

I tried `snap refresh` then `snap run cncra2yr.cncra2yrogl`.

**Comment by mmtrt** [comment]
Did you tried without ogl launch command see if this still happen

**Comment by edos4** [comment]
I also tried `snap run cncra2yr`. 

I also tried all the renderers, restarting the game each time I change renderer.

**Comment by mmtrt** [comment]
I also tried to reproduce this issue but couldn't on fresh install of snap.

maybe try fresh install with purge remove of snap.

`snap remove --purge cncra2yr`

**Comment by edos4** [comment]
I tried purging. Then reinstalled. Still not working. 

However, there's this: `ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.`

**Comment by mmtrt** [comment]
post logs from `/home/$USER/snap/cncra2yr/common/.wine/drive_c/Westwood/RA2/Client/`

**Comment by edos4** [comment]
[client.log](https://github.com/mmtrt/cncra2yr/files/5394788/client.log)

[ClientCrashLog_2_10_2020_20_34.txt](https://github.com/mmtrt/cncra2yr/files/5394789/ClientCrashLog_2_10_2020_20_34.txt)

[ClientCrashLog_2_10_2020_20_35.txt](https://github.com/mmtrt/cncra2yr/files/5394790/ClientCrashLog_2_10_2020_20_35.txt)

**Comment by edos4** [comment]
@mmtrt , please help?

**Comment by mmtrt** [comment]
Try these in terminal

```
export __NV_PRIME_RENDER_OFFLOAD="1"
export
__GLX_VENDOR_LIBRARY_NAME="nvidia"
export __VK_LAYER_NV_optimus="NVIDIA_only"
```

Than launch game from same terminal

`cncra2yr`

See if this helps though I'm out of ideas why this doesn't work for you.

**Comment by edos4** [comment]
Hi. Thank you, but it is still not working. Will try other ways and update here when it's fixed.

**Comment by mmtrt** [comment]
can you try build from edge branch see if you still have issue.

**Comment by mmtrt** [comment]
> When I try to Launch Game on Skirmish, .... Then it returns to the Skirmish menu.

I had this similar when testing new changes on snap it was because of missing required game dll files from `/home/$USER/snap/cncra2yr/common/.wine/drive_c/Westwood/RA2/`

```
BINKW32.dll
BLOWFISH.dll
```

**Comment by edos4** [comment]
Confirming that my those 2 DLL files are 0kb. Thank you. Will try downloading the game again and update here.

**Comment by edos4** [comment]
Got to play it again, thanks for saving my life, @mmtrt ! :)
