### ISSUE TITLE
Main Menu works, game won't start

### ISSUE THREAD

**Issue by Nixellion** [mmtrt/cncra2yr#24]
I was going to test the game on Skirmish, but it does not start. Menu goes out of fullscreen mode, and that's it. On Windows a second game window shows up, but here - nope.

Same with online stuff. Looks like it can't launch the actual game for some reason, only main menu and cncnet quickmatch thing.

**Comment by mmtrt** [comment]
anything in logs, does it come back to main menu after starting game?

**Comment by Nixellion** [comment]
I tried running snap from command line, nothing in the logs there. Where else can I look for logs?

And yes it jumps back to the menu after that. I think. I mean it's not going away, it stays open all the time, just gets out of focus when the game is supposed to be launching. Like it tried to open another app and switch to it, but it crashed?

**Comment by Nixellion** [comment]
Abort, that was just permission error, copied some files as root. Chowned and it works fine now.

No music though, any idea which files I forgot to copy? All 6 that were listed I did copy over. Music volume is turned up in settings.

**Comment by mmtrt** [comment]
Ah that's good to hear, as for music on main menu that just doesn't work here as well so that's expected.
