### ISSUE TITLE
Alt-tabbing freezes the game

### ISSUE THREAD

**Issue by foodornt** [mmtrt/cncra2yr#25]
switching to any other workspace freezes the game

tried setting `noactivateapp` to `true` in cnc-ddraw.ini, but no luck

any idea how to fix this?

**Comment by mmtrt** [comment]
did you tried changing renderer from launcher setting? if issue it still happens then try using wine virtual desktop from winecfg
`cncra2yr.wine winecfg` should be in graphics tab.

**Comment by foodornt** [comment]
Using a virtual desktop with my screen resolution (1920x1080) fixed the issue

now I can recover my childhood memories, thank you
