### ISSUE TITLE
Where do I put the RA2 base files??

### ISSUE THREAD

**Issue by vocatus** [mmtrt/cncra2yr#7]
Hi there, I downloaded your snap pack, but not sure where to put the RA2 base files?

**Comment by mmtrt** [comment]
instructions clearly stated in repo readme as well on starting snap the a dialog shows info. I think you need `YR` files to in order to get it working.
> Requirements
> * Original game files of Red Alert 2 Yuri's Revenge.
> ``BINKW32.dll
> BLOWFISH.dll
> ra2.mix
> ra2md.mix
> language.mix
> langmd.mix``
> 
> During Installation
> * Copy game files to `$HOME/snap/cncra2yr/common/.wine/drive_c/Westwood/RA2` when snap ask to install game and it also ask user to allow it to open above game install dir.

**Comment by vocatus** [comment]
Ah, my apologies, I was only looking at the snap page. Thanks!
